const { chromium } = require('C:/Users/mahen/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs = require('node:fs');
const path = require('node:path');

const output = path.resolve(__dirname, '../artifacts/submission');
async function main() {
  fs.mkdirSync(path.join(output, 'screenshots'), {recursive:true});
  fs.mkdirSync(path.join(output, 'raw'), {recursive:true});
  const browser = await chromium.launch({headless:true});
  const context = await browser.newContext({viewport:{width:430,height:900},deviceScaleFactor:2,recordVideo:{dir:path.join(output,'raw'),size:{width:430,height:900}}});
  const page = await context.newPage();
  const errors=[];
  page.on('pageerror', e=>errors.push(String(e)));
  await page.goto('http://127.0.0.1:5173', {waitUntil:'networkidle'});
  await page.getByTestId('create-outing-room').waitFor();
  const scenes=[];
  const started=Date.now();
  async function shot(name, seconds=3) {
    await page.screenshot({path:path.join(output,'screenshots',name+'.png')});
    scenes.push({name,time:(Date.now()-started)/1000});
    console.log('Captured '+name);
    await page.waitForTimeout(seconds*1000);
  }
  await shot('01-home',5);
  await page.getByTestId('create-outing-room').click();
  await shot('02-create',4);
  await page.getByTestId('launch-room').click();
  await shot('03-brief',6);
  await page.getByRole('button',{name:'Toggle transcript',exact:true}).click();
  await shot('04-captions',3);
  await page.getByRole('button',{name:'Expand stage',exact:true}).click();
  await shot('05-expanded',3);
  await page.getByRole('button',{name:'Let RoundTable work',exact:true}).click();
  await page.getByText('Finding common ground',{exact:true}).waitFor();
  await shot('06-search',1);
  await page.getByText('The trade-offs, side by side',{exact:true}).waitFor();
  await shot('07-compare',7);
  await page.getByRole('button',{name:'Ask the room to vote',exact:true}).click();
  await shot('08-vote-start',3);
  await page.getByRole('button',{name:'Simulate You vote',exact:true}).click();
  await page.waitForTimeout(700);
  await page.getByRole('button',{name:'Simulate Priya vote',exact:true}).click();
  await page.waitForTimeout(700);
  await page.getByRole('button',{name:'Simulate Ayaan vote',exact:true}).click();
  await shot('09-vote-complete',5);
  await page.getByRole('button',{name:'Review proposed action',exact:true}).click();
  await shot('10-approve',6);
  await page.getByRole('button',{name:'Approve demo calendar action',exact:true}).click();
  await page.getByText('A decision with a receipt',{exact:true}).waitFor();
  await shot('11-receipt',7);
  await page.getByRole('button',{name:'Rain changes plans',exact:true}).click();
  await page.getByRole('button',{name:'Let RoundTable work',exact:true}).click();
  await page.getByText('The trade-offs, side by side',{exact:true}).waitFor();
  await shot('12-rain',5);
  await page.getByRole('button',{name:'Leave early',exact:true}).click();
  await shot('13-early',4);
  await page.getByRole('button',{name:'Leave room',exact:true}).click();
  await page.getByTestId('tab-profile').click();
  await page.getByRole('button',{name:'Open Agora voice',exact:true}).click();
  await shot('14-agora',7);
  await page.getByRole('button',{name:'Back to profile',exact:true}).click();
  await page.getByTestId('tab-home').click();
  await shot('15-close',3);
  const video=page.video();
  await context.close();
  await video.saveAs(path.join(output,'raw','roundtable-product-walkthrough.webm'));
  await browser.close();
  fs.writeFileSync(path.join(output,'capture-manifest.json'),JSON.stringify({scenes,errors,duration:(Date.now()-started)/1000},null,2));
  if(errors.length) throw new Error('Browser runtime errors: '+errors.join('\n'));
  console.log('Actual interactive walkthrough recorded and verified.');
}
main().catch(e=>{console.error(e);process.exitCode=1});
